---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ambbatxv/boostaddis.ambbatech.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -a dist/. $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    